name: Delete Packages Starting with sha

on:
  workflow_dispatch:

jobs:
  delete_packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: actions/delete-package-versions@v4
        with: 
          package-name: 'package'
          package-type: 'container'
          min-versions-to-keep: 1
          delete-only-untagged-versions: 'true'
